services:
  gateway:
    image: traefik:v3.7.1

    # container_name: coruja-gateway

    command:
    - "--api.dashboard=true"
    - "--api.insecure=true"

    - "--providers.docker=true"
    - "--providers.docker.exposedbydefault=false"

    - "--providers.file.directory=/etc/traefik/dynamic"
    - "--providers.file.watch=true"

    - "--entrypoints.web.address=:80"
    - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
    - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
    - "--entrypoints.web.http.redirections.entrypoint.permanent=true"

    - "--entrypoints.websecure.address=:443"

    ports:
      - "${HTTP_PORT}:80"
      - "${HTTPS_PORT}:443"
      - "${TRAEFIK_DASHBOARD_PORT}:8080"

    volumes:
    - "/var/run/docker.sock:/var/run/docker.sock:ro"
    - "./config/traefik/dynamic:/etc/traefik/dynamic:ro"
    - "./certs:/etc/traefik/certs:ro"

    restart: unless-stopped

    networks:
      - coruja-network

  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USERNAME: developer
        USER_UID: ${USER_UID:-1000}
        USER_GID: ${USER_GID:-1000}

    # container_name: coruja-php83-apache

    volumes:
      - "${PROJECTS_ROOT}:/var/www/projects"

    extra_hosts:
      - "host.docker.internal:host-gateway"

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.projects.rule=HostRegexp(`^[a-z0-9-]+\\.localhost$`)"
      - "traefik.http.routers.projects.entrypoints=websecure"
      - "traefik.http.routers.projects.tls=true"
      - "traefik.http.routers.projects.priority=10"
      - "traefik.http.services.projects.loadbalancer.server.port=80"
    
    depends_on:
      database:
        condition: service_healthy

      redis:
        condition: service_healthy
      
      mail:
       condition: service_started

    restart: unless-stopped

    networks:
      - coruja-network

  database:
    image: mariadb:11.8.8

    # container_name: coruja-mariadb11

    ports:
      - "${DB_PORT}:3306"

    environment:
      MARIADB_ROOT_PASSWORD: "${MARIADB_ROOT_PASSWORD}"
      MARIADB_DATABASE: "${MARIADB_DATABASE}"
      MARIADB_USER: "${MARIADB_USER}"
      MARIADB_PASSWORD: "${MARIADB_PASSWORD}"

    volumes:
      - "${DB_DATA_PATH}:/var/lib/mysql"

    healthcheck:
      test:
        - CMD
        - healthcheck.sh
        - --connect
        - --innodb_initialized
      interval: 10s
      timeout: 5s
      retries: 10

    restart: unless-stopped

    networks:
      - coruja-network

  phpmyadmin:
    image: phpmyadmin:5.2.3-apache

    # container_name: coruja-phpmyadmin

    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      UPLOAD_LIMIT: 128M

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.phpmyadmin.rule=Host(`db.localhost`)"
      - "traefik.http.routers.phpmyadmin.entrypoints=websecure"
      - "traefik.http.routers.phpmyadmin.tls=true"
      - "traefik.http.routers.phpmyadmin.priority=100"
      - "traefik.http.services.phpmyadmin.loadbalancer.server.port=80"

    depends_on:
      database:
        condition: service_healthy

    restart: unless-stopped

    networks:
      - coruja-network

  redis:
    image: redis:8.8.0-alpine

    # container_name: coruja-redis

    command:
      - redis-server
      - --appendonly
      - "yes"
      - --appendfsync
      - everysec

    volumes:
      - "${REDIS_DATA_PATH}:/data"

    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      interval: 10s
      timeout: 5s
      retries: 10

    restart: unless-stopped

    networks:
      - coruja-network

  mail:
    image: axllent/mailpit:v1.30.0

    # container_name: coruja-mail

    restart: unless-stopped

    networks:
      - coruja-network

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mail.rule=Host(`mail.localhost`)"
      - "traefik.http.routers.mail.priority=100"
      - "traefik.http.routers.mail.entrypoints=websecure"
      - "traefik.http.routers.mail.tls=true"
      - "traefik.http.services.mail.loadbalancer.server.port=8025"

networks:
  coruja-network:
    driver: bridge
