APP_NAME="{{PROJECT_NAME}}"
APP_ENV=development
APP_DEBUG=true
APP_URL=http://{{PROJECT_NAME}}.localhost

DB_HOST=database
DB_PORT=3306
DB_DATABASE={{DATABASE_NAME}}
DB_USERNAME={{MARIADB_USER}}
DB_PASSWORD={{MARIADB_PASSWORD}}

REDIS_HOST=redis
REDIS_PORT=6379
REDIS_DATABASE=0