#!/usr/bin/env bash

CORUJA_HOME="${CORUJA_HOME:-$HOME/www}"

CORUJA_PROJECTS_DIR="${PROJECTS_ROOT:-${CORUJA_HOME}/projects}"
CORUJA_DATABASE_DIR="${DB_DATA_PATH:-${CORUJA_HOME}/data/mariadb}"
CORUJA_REDIS_DIR="${REDIS_DATA_PATH:-${CORUJA_HOME}/data/redis}"
CORUJA_BACKUPS_DIR="${BACKUPS_PATH:-${CORUJA_HOME}/backups}"
CORUJA_TEMPLATES_DIR="${TEMPLATES_PATH:-${CORUJA_HOME}/templates}"