CORUJA_HOME="$HOME/www"

CORUJA_PROJECTS_DIR="$CORUJA_HOME/projects"
CORUJA_DATABASE_DIR="$CORUJA_HOME/data/mariadb"
CORUJA_REDIS_DIR="$CORUJA_HOME/data/redis"
CORUJA_BACKUPS_DIR="$CORUJA_HOME/backups"
CORUJA_TEMPLATES_DIR="$CORUJA_HOME/templates"